name: sonarscan
on: push
jobs:
    hosting:
      name: sonar cloud
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - name: code 
          uses: actions/checkout@v1
        - name: sonar scan
          uses: 
