name: sonarscan & osv scanner
on: push
jobs:
    hosting:
      name: sonar cloud
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - name: code 
          uses: actions/checkout@v1
        # - name: sonar scan
        #   uses: SonarSource/sonarcloud-github-action@master
        #   env:
        #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        - name: osv scanner
          run: |
            go install github.com/google/osv-scanner/cmd/osv-scanner@v1.6.2

            osv-scanner --sbom=./sbom.spdx.json  --json >> ./osv-results.json || exit_code=$?
