name: Build and Release flutter based webapp
on:
  # push:
  #      branches:
  #      - master

  workflow_dispatch: {}
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        # - uses: subosito/flutter-action@v1
        #   with:
        #     channel: 'dev'

        # # Build Website
        # - name: Build Website
        #   run: |
        #     flutter config --enable-web
        #     flutter build web

        # Deploy Firebase Hosting
       # - name: Deploy Firebase Hosting
        #  uses: w9jds/firebase-action@master
         # with:
          # args: deploy:production-weapp
          #env:
          # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
           #PROJECT_PATH: ./build/web
        # - name: creating container env
        #   uses: docker/setup-buildx-action@v1
        # - name: docker login 
        #   uses: docker/login-action@v1
        #   env:
        #       GIT_USER: ${{ github.actor}}
        #       GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   with:
        #    registry: ghcr.io
        #    username: $env.GIT_USER
        #    password: ${{ env.GIT_TOKEN }}
        # - name: build & publish docker image
        #   uses: docker/build-push-action@v2
        #   env: 
        #       REGISTRY: ghcr.io
        #   with:
        #    context: .
        #    file: ./Dockerfile
        #    push: true
        #    tags: ${{ env.REGISTRY }}/${{ github.repository }}/flutter:1
        
        # - name: listing images
        #   run: 
        #      docker images

        # - uses: actions/setup-go@v5
        #   with:
        #    go-version: '^1.17'
        # - name: osv scanner
        #   run: |
        #     curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
        #     ./syft ghcr.io/hellonanda/flutter_testing_app/flutter:1 --scope all-layers -o spdx-json=sbom.spdx.json
            
        #    



      

        
        # - name: sonar scan
        #   uses: SonarSource/sonarcloud-github-action@master
        #   env:
        #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # - uses: actions/setup-go@v5
        #   with:
        #    go-version: '^1.17'
        # - name: osv scanner
        #   run: |
        #     curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
        #     ./syft apps_ci:latest --scope all-layers -o spdx-json=sbom.spdx.json
            
        #     go install github.com/google/osv-scanner/cmd/osv-scanner@v1
        #     osv-scanner --sbom=./sbom.spdx.json  --json >> ./osv-results.json || exit_code=$?

        - name: Run Load Test
          uses: apardo04/locust-github-action@master
          with:
           URL:  "https://api.nftix-d2-stg.sncs-sw3.jp/docs"
           USERS: "5000"
           RATE: "500"
           RUNTIME: "1000s"
       
